### ISSUE TITLE
Provide a custom style to cli execution.

### ISSUE THREAD

**Issue by ascariandrea** [renke/import-sort#1]
Hi @renke,
I'm planning to use your library in our workflow cause we like to keep the imports order shared across the team.
Anyway, my concern is about passing a custom style in the *cli* command.
Are you already working on this? Do you need help to achieve this?

Let me know, 
have a nice day.

**Comment by renke** [comment]
Hi @ascariandrea ,

I am not currently working on that feature but I would definitely accept a pull request. It should not be too hard to implement, because you can just pass a different style to the `importSort` function already, It's just not exposed to the CLI in any way currently.
