### ISSUE TITLE
how to disable import sort by comment

### ISSUE THREAD

**Issue by lovemyliwu** [renke/import-sort#11]
I'm using import-sort-cli, in README said disable sort by comment is support now, but I can't see it.

here is my code:

```
// eslint-disable line
import $ from 'jquery';// eslint-disable line
// d
import 'fixed-sticky/fixedsticky.js';// eslint-disable line
//d 
```

**Comment by renke** [comment]
Hi @lovemyliwu, 

there is currently no plan to exclude certain imports from being sorted. 

The comment in the README refers to the fact that import-sort now leaves comments as is (most of the time) such that `// eslint-disable-line` can now be used to control ESLint's behaviour.

I am closing it for now, but I will keep the idea in mind.
