### ISSUE TITLE
Suggestion: add simple sorting rules

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [renke/import-sort#13]
It is nice extension but unfortunately i cannot use it because of import order does not fit team agreement.
So it would be great if there be a possibility to define simple rules set in unserConfig without writing new sorter. For instance:

```
sortImports.rule: (importValue: string) => { 
    if(importValue.contains('angular') { return 1 }; 
    if(importValue.endsWith('.less') { return 3 }; 
    return 2;
}
```
 

higher return value lower place where the import appears (in this case angular goes first, less - goes last, all others goes in between)

Also there will be cool to introduce option to skip new line between different import categories because different teams has different rules and ide'as so you cannot enforce to have new lines.

**Comment by renke** [comment]
Hi @vytautas-pranskunas- 

unfortunately, to do this you have to write your own style. See https://github.com/renke/import-sort#writing-you-own-custom-style for more information.
