### ISSUE TITLE
Documentation typo: import-sort-babylon does not exist

### ISSUE THREAD

**Issue by joepsz** [renke/import-sort#14]
Thanks for creating this project! Love it. 

I was kind of confused while configuring, since I could not find the `import-sort-babylon` repo that you mention in the readme.

> To use it you probably want to install import-sort, import-sort-config, a parser (say import-sort-babylon) and a style (say import-sort-style-eslint).

Since you also mentioned `import-sort-parser-babylon` a paragraph before that, it didn't take long for me to figure out what the correct name was.

**Comment by renke** [comment]
HI @joepsz,

thank you very much! The typo will be fixed with next push!
