### ISSUE TITLE
Sort on save does not work anymore

### ISSUE THREAD

**Issue by eTorAken** [renke/import-sort#16]
Hello,

My team is experiencing an issue with the "Sort on save" option. We are running on Atom v1.13+. It may be related with [remote-sync](https://github.com/yongkangchen/remote-sync) plugin which allow FTP uploads on save.

Did you experienced this issue as well?

**Comment by renke** [comment]
Hi @eTorAken 

works for me. This may be related to the remote-sync plugin you mentioned. I am closing it for now. If you have more information, just create a new issue!

**Comment by eTorAken** [comment]
Hello @renke,

I got more informations about this fail. We actually do not install npm dependencies on our local machine (we do this on the remote). We still install needed dependencies in global to keep using Atom tools (such as linters and import-sort) but it does not work with `import-sort`.

In Atom, `Ctrl + Alt + o` throws `Failed to sort imports: Error: Cannot find module 'import-sort-parser-babylon'` (which "Sort on Save" option does not show btw).

I got `import-sort`, `babylon` and even `import-sort-parser-babylon` installed as global.

**Comment by renke** [comment]
Hi @eTorAken 

internally import-sort (or rather import-sort-config) uses [resolve-from](https://www.npmjs.com/package/resolve-from) to resolve the parser and style that is used. 

I recommend to add the parser and style as devDependency to your applications package.json and install it locally like the rest of your dependencies.

**Comment by eTorAken** [comment]
Hey,

As I said, I do not want to install these packages as project dependencies. I want to use them as global dependencies (e.g. `npm install -g`) and to manage project dependencies through my remote machine.

That's what I currently have on my local machine:
```sh
$ npm ls -g --depth=0
+-- import-sort@3.2.0
+-- import-sort-config@3.2.0
+-- import-sort-parser-babylon@3.2.0
+-- import-sort-style-module@3.0.0
`-- resolve-from@3.0.0
```

It still gives me the `Failed to sort imports: Error: Cannot find module 'import-sort-parser-babylon'` error when I try to sort with `Ctrl` + `Alt` + `o`.

JSYK, ESLint works well with global installation, it has a specific option for that which is "Use global ESLint installation"
![ESLint global installation option](https://i.gyazo.com/c5c41f88d3fe6bdf79c671a5f38871a9.png)

Maybee that's something not implemented in `import-sort` yet, which would be nice to have 😄

**Comment by renke** [comment]
Hi @eTorAken,

mh, I see, this is currently not supported because require doesn't load packages that installed globally. 

I could use something like [requireg](https://www.npmjs.com/package/requireg) to allow global packages to be loaded. If I find some time, I try to see if that works.

As an alternative, you could also try to set your NODE_PATH such that it considers global packages as well (see https://stackoverflow.com/a/15646750 for more details).

**Comment by eTorAken** [comment]
Hi @renke,

I just tried the alternative. I didn't manage to make it work with the NODE_PATH but I tried a simple `npm link` which works like a charm!

That's what I did:
```bash
npm install import-sort-style-module --global
cd ~/myProjectFolder
npm link import-sort-style-module
```

`import-sort-style-module` is the only required module to make it work fyi.

Thanks for your help!
