### ISSUE TITLE
Import sorting doesn't follow eslint rules

### ISSUE THREAD

**Issue by jimklo** [renke/import-sort#17]
This is certainly a new feature, however it's somewhat of a bug, since anyone using eslint will have the problem with the sorting rules being incorrect.

See:
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md

It would be great if sorting could honor the eslint sorting rules in effect.

**Comment by renke** [comment]
Hi @jimklo 

Does eslint-plugin-import contains some extra rules that are not part of the default ESLint rule set? – If that's the case, I think it would be the correct way to write a new style that conforms to those rules.

**Comment by renke** [comment]
See #9.
