### ISSUE TITLE
Support ESLint sort-imports ignoreCase option

### ISSUE THREAD

**Issue by keithkml** [renke/import-sort#20]
Our`.eslintrc`: 
```
{
  "parser": "babel-eslint",
  "rules": {
    "sort-imports": [2, {"ignoreCase": true}]
  }
}
```

The following input is already sorted, and produces 0 errors with ESLint's `sort-imports` rule:

```js
import type {AccountType} from '../../../types/thrift/yellow/yellow';
import {connectToStyles} from '@uber/superfine-react';
import isEqual from 'lodash/isEqual';
import {LocationMap} from './map';
import LocationModal from './location-modal';
import {matches} from './utils';
import {NEW_LOCATION_UUID} from './constants';
import React from 'react';
import ReactDOM from 'react-dom';
import Search from '@uber/react-inline-icons/search';
import type {SuperfineStylePropType} from '../../../util/types';
import t from '../../../util/i18n';
import {TextInput} from '@uber/react-inputs';
```

After running `import-sort`, I get:

```diff
 import type {AccountType} from '../../../types/thrift/yellow/yellow';
-import {connectToStyles} from '@uber/superfine-react';
-import isEqual from 'lodash/isEqual';
 import {LocationMap} from './map';
 import LocationModal from './location-modal';
-import {matches} from './utils';
 import {NEW_LOCATION_UUID} from './constants';
 import React from 'react';
 import ReactDOM from 'react-dom';
 import Search from '@uber/react-inline-icons/search';
 import type {SuperfineStylePropType} from '../../../util/types';
+import {TextInput} from '@uber/react-inputs';
+import {connectToStyles} from '@uber/superfine-react';
+import isEqual from 'lodash/isEqual';
+import {matches} from './utils';
 import t from '../../../util/i18n';
-import {TextInput} from '@uber/react-inputs';
```

Unfortunately this file now produces an error in ESLint:
```
index.js
  13:1  error  Imports should be sorted alphabetically                     sort-imports
```

**Comment by renke** [comment]
Hi @keithkml 

the original goal of the ESLint style was to track the default setting of the sort-imports rule. To support options like ignoreCase we need way to read final ESLint config that applies to a given file. Unless ESLint's [Node.js API](http://eslint.org/docs/developer-guide/nodejs-api) offers a way to that, this will be hard to implement in an elegant manner. I try to see if it's possible though and let you know.

**Comment by renke** [comment]
The fix is now released with 3.0.

**Comment by keithkml** [comment]
Hi, I am very excited that you worked on this! Unfortunately it doesn't work at all for me – it does not pick up my ESLint readonly setting no matter what I try. Unfortunately our project is huge and I haven't had time to whittle it down to a reproducible test case. Just wanted to say thanks for addressing my issue so quickly, and I'm sorry I haven't been able to debug. (Getting married this weekend so things have been a little crazy :)

**Comment by renke** [comment]
Hi @keithkml 

I will close this for now. I will try to polish the `eslint` style in the future though.

Also, congratulations for getting married :tada:
