### ISSUE TITLE
Have configs stored in a separate config file?

### ISSUE THREAD

**Issue by magicmark** [renke/import-sort#24]
This would allow for shared import-sort configs

something like `import-sort.config.js`?

**Comment by renke** [comment]
Hi @magicmark 

for the next major release I intend to replace the current config system with https://github.com/davidtheclark/cosmiconfig which supports JavaScript-based configuration. I hope that will solve your use case.

Thanks for your support!

**Comment by renke** [comment]
Hi @magicmark 

this is now part of major version 4.
