### ISSUE TITLE
Request: add support to relative aliases in 'module' style

### ISSUE THREAD

**Issue by fsmaia** [renke/import-sort#26]
When developing with Webpack, is common to set `resolve.alias` to configure relative path aliases, such as `actions`, `components`. As 'module' style doesn't know these aliases, they are considered absolute modules instead of relative.

To quickly fix this problem I forked the import sort style module and hardcoded some aliases: https://github.com/fsmaia/import-sort-style-module-relative-aliases

It would be very nice to add this support in settings, or even reading it from webpack.config.js or any alias support tool.

**Comment by ruanyl** [comment]
@fsmaia Actually you can read `package.json` in your own style module, then have `resolve.alias` settings in `package.json`. I have a workaround here that may help you a bit: https://github.com/ruanyl/import-sort-style-alias

**Comment by renke** [comment]
Hi @fsmaia 

with the new major version 4 custom configuration options are now passed to a style. So something like:

```json
  "importSort": {
    ".js, .jsx, .es6, .es": {
      "parser": "babylon",
      "style": "alias",
      "custom": {
        "alias": ["components", "modules"]
      }
    },
    ".ts, .tsx": {
      "parser": "typescript",
      "style": "alias",
      "custom": {
        "alias": ["components", "modules"]
      }
    }
```

will be exposed to your style (e.g. `(styleApi: IStyleAPI, file?: string, options?: any) => …`) as `options.alias`. Let me know if that helps.
