### ISSUE TITLE
Custom sorting is not working

### ISSUE THREAD

**Issue by sergeyzwezdin** [renke/import-sort#30]
Hi!

Thank you for you import-sort tool, it's very useful.

I'm using VS Code plugin and have a trouble with sort customization.

I've added configuration into `package.json`:

```
    "importSort": {
        ".js, .jsx, .es6, .es": {
            "parser": "babylon",
            "style": "module"
        }
    }
```

But when I try to save my JS-file it works as before:

```
import { Text, TouchableOpacity, View } from 'react-native';

import React from 'react';
import styled from 'styled-components/native';
import { withNavigation } from 'react-navigation';
```

I believe plugin is not reading `package.json` config during his work. Any ideas how to fix that?

**Comment by renke** [comment]
Hi @sergeyzwezdin 

please try again with the new major version 4. Currently there is no error checking regarding parsing of the configuration and `import-sort` will fall back to its default configuration.

**Comment by sergeyzwezdin** [comment]
Thank you!
