### ISSUE TITLE
Only one file or directory can be specified

### ISSUE THREAD

**Issue by IgnusG** [renke/import-sort#31]
How do I specify several files? I am currently just calling import-sort with every directory but there are pre-commit linters in my code that only pass a list of files to be commited.

**Comment by swansontec** [comment]
This is an issue for me as well. I tried to use import-sort with the [lint-staged](https://www.npmjs.com/package/lint-staged) tool, but lint-staged passes multiple files to each tool.

**Comment by IgnusG** [comment]
@swansontec that was exactly my problem. Since then I already created a PR that solves this and published `multifile-import-sort-cli` until it’s merged. It also contains the https://github.com/renke/import-sort/pull/33 PR which is important for lint-staged to work properly

**Comment by renke** [comment]
Hi @IgnusG 

I just released major version 4. The CLI now basically behaves like prettier's CLI. Let me know if that fixes your problem.
