### ISSUE TITLE
isNodeModule matcher only works for built-ins

### ISSUE THREAD

**Issue by OliverJAsh** [renke/import-sort#34]
I would like to group *all* my node modules, built-in and installed, separately from other absolute imports. However the `isNodeModule` helper only infers built-in node modules like `fs` and `path`. Could it be extended to also include manually installed node modules?

As an example, using the module style, I am seeing:

``` ts
import path from 'path';

import React from 'react';
```

… when I want:

``` ts
import path from 'path';
import React from 'react';
```

**Comment by OliverJAsh** [comment]
I guess we would know more if we had the whole path? This is what `eslint-plugin-import` does https://github.com/benmosher/eslint-plugin-import/blob/cd771330d2c487dfb486c5d333ac0c37a4d4d2f2/src/core/importType.js#L30

**Comment by OliverJAsh** [comment]
I got it working with this patch. Would you be happy for me to raise a PR with these changes?

``` patch
diff --git a/node_modules/import-sort/lib/style/StyleAPI.js b/node_modules/import-sort/lib/style/StyleAPI.js
index e275761..e26d985 100644
--- a/node_modules/import-sort/lib/style/StyleAPI.js
+++ b/node_modules/import-sort/lib/style/StyleAPI.js
@@ -1,6 +1,21 @@
 "use strict";
 Object.defineProperty(exports, "__esModule", { value: true });
-const isNodeModulePredicate = require("is-builtin-module");
+const isBuiltInNodeModulePredicate = require("is-builtin-module");
+const pathModule = require("path");
+
+const EXTERNAL_FOLDERS = ["node_modules"];
+
+const isExternalFolderPredicate = (path, name) =>
+  EXTERNAL_FOLDERS.some(folder => path.includes(pathModule.join(folder, name)));
+
+function tryCatch (fn) {
+  try {
+    return fn();
+  } catch (error) {
+    return undefined;
+  }
+}
+
 function member(predicateOrComparator) {
     if (predicateOrComparator.length === 1) {
         const predicate = predicateOrComparator;
@@ -94,8 +109,15 @@ function hasMultipleMembers(imported) {
 function hasSingleMember(imported) {
     return (imported.namedMembers.length + (imported.defaultMember ? 1 : 0)) === 1 && !hasNamespaceMember(imported);
 }
+function isExternalNodeModulePredicate(moduleName) {
+  const maybePath = tryCatch(() => require.resolve(moduleName));
+  return maybePath !== undefined ? isExternalFolderPredicate(maybePath, moduleName) : false;
+};
 function isNodeModule(imported) {
-    return isNodeModulePredicate(imported.moduleName);
+  return (
+    isExternalNodeModulePredicate(imported.moduleName) ||
+    isBuiltInNodeModulePredicate(imported.moduleName)
+  );
 }
 function isRelativeModule(imported) {
     return imported.moduleName.indexOf(".") === 0;

```

**Comment by OliverJAsh** [comment]
Ping @renke. Would be good to get this fixed! Happy to raise a PR, just let me know what you think.

**Comment by renke** [comment]
I am a bit short on time right now. I will work on this (and all other issues) as soon as possible!

**Comment by renke** [comment]
Hi @OliverJAsh 

just to clarify what you want. You want to distinguish between built-in modules (say `fs), installed modules ("react") and your modules (using an webpack alias)?

**Comment by OliverJAsh** [comment]
That's right @renke.

Here is the desired sort order:

```
// built in node modules

// external node modules

// modules using webpack aliases, e.g. `components/foo`
```

**Comment by OliverJAsh** [comment]
Coming back to this now.

I want to group all Node modules together, regardless of whether it's a built in or external Node module.

The patch I included above fixes `isNodeModule` to include external Node modules. Currently it only considers built in Node modules.

I can see others wanting to separate built in and external Node modules as well, however that is not what I'm trying to achieve.

Here is my desired template:

```
// all node modules, built in (e.g. fs) and external (e.g. react) imports

// all webpack alias folder except "components", e.g. "reducers", "helpers" imports

// webpack alias folder "components" imports

// relative imports
```

If we fix the definition of `isNodeModule`, as per this issue, I am able to write a custom style to match this template:

https://github.com/OliverJAsh/import-sort-style-unsplash/commit/79be15fe293b5dca8dd3493680244aad221424b2

**Comment by OliverJAsh** [comment]
I attempted to raise a PR for this, but I couldn't find documentation for contributing (e.g. how to use lerna with this project). I tried to run `yarn` and `lerna bootstrap` but ran into issues with both.

**Comment by renke** [comment]
Hi @OliverJAsh 

so, a new function `startsWith(...prefix)` that can be used like `moduleName(startsWith("components"))` would solve your problem?

**Comment by OliverJAsh** [comment]
Hi @renke!

Not quite. I just realised the example in my original post was wrong and misleading. I've updated it now. Below is the corrected example.

Currently, using the module style, I get:

``` ts
// group for built-in Node modules
import path from 'path';

// external Node modules are not considered Node modules, but instead considered absolute
import React from 'react';
```

… when I want:

``` ts
// all Node modules: built-in and external
import path from 'path';
import React from 'react';
```

In order to achieve this, we need to fix `isNodeModule` to consider "external" node modules (like `react`) as well as "built in" Node modules (like `path`). I want external and built-in Node modules to be grouped together—a single group for all Node modules, external and built-in.

I achieved this with the modifications shown in this patch: https://github.com/renke/import-sort/issues/34#issuecomment-331306172. I would like to get these changes added to the core version, if possible.

**Comment by renke** [comment]
Then maybe something like `and(not(moduleName(startsWith(...), isAbsoluteModule)`?

**Comment by OliverJAsh** [comment]
@renke I don't think that would quite solve my problem either.

Here is my desired template:

```
// all node modules, built-in (e.g. fs) and external (e.g. react) imports

// all webpack alias folders except "components", e.g. "reducers", "helpers" imports

// webpack alias folder "components" imports

// relative imports
```

For example:

``` ts
// all node modules, built-in (e.g. fs) and external (e.g. react) imports
import React, { StatelessComponent, SFC } from 'react';
import { Link } from 'react-router-dom';
import { connect, MapStateToProps } from 'react-redux';
import classNames from 'classnames';
import { Option } from 'funfix-core/dist/umd';
import path from 'path';
import fs from 'fs';

// all webpack alias folders except "components", e.g. "reducers", "helpers" imports
import { getIsLoggedIn } from 'reducers/auth-reducer';
import { VARIANTS as HOMEPAGE_HEADER_VARIANTS } from 'xp/HOMEPAGE_HEADER';
import { getHomepageHeaderXp } from 'reducers/xp-reducer';
import { buildUserPathname } from 'helpers/links';
import { LICENSE_PATHNAME } from 'constants/pathnames';

// webpack alias folder "components" imports
import AdminNav from 'components/AdminNav';
import BottomBar from 'components/BottomBar';
import LoginModal from 'components/LoginModal';

// relative imports
import Buttons from './components/Buttons';
import { BackgroundImage, BackgroundImageProps } from './components/BackgroundImage';
import styles from './FeedHeader.css';
import { BackgroundMode } from './FeedHeader-helpers';
import Search, { OwnProps as SearchProps } from './components/Search';
```

If we fix the definition of `isNodeModule`, as per this issue, I am able to write a custom style to match this template:

https://github.com/OliverJAsh/import-sort-style-unsplash/commit/79be15fe293b5dca8dd3493680244aad221424b2

**Comment by renke** [comment]
Hi @OliverJAsh,

the thing is, we can't just change `isNodeModule` because that could break other styles. I see what you want to do now. You want a function that checks if a module is located in "node_modules". And most aliased modules are located outside of "node_modules". Correct? 

Any idea for a good name of that function? -- I think a isExternalModule that checks if the given module is not in "node_modules" would be okay?

**Comment by renke** [comment]
Mhh, thinking about it, using require.resolve won't work because it doesn't understand webpack aliases. How does your solution deal with that?

**Comment by OliverJAsh** [comment]
@renke If we want to check if the Node module is in `node_modules`, `require.resolve` should tell us that, because we'll get the full path. But I see your point, I think—if the module ID is aliased in webpack, it won't be recognised as such by `require.resolve`.

In our case, we don't have any webpack aliases like that, so `require.resolve` is sufficient enough.

**Comment by OliverJAsh** [comment]
> You want a function that checks if a module is located in "node_modules". And most aliased modules are located outside of "node_modules". Correct?

That's correct :-)



> Any idea for a good name of that function? -- I think a isExternalModule that checks if the given module is not in "node_modules" would be okay?

"External" is a bit ambiguous. Perhaps `isInstalledNodeModule` as a function that checks if the module lives in `node_modules`?

**Comment by renke** [comment]
Hi @OliverJAsh 

I published a new minor version (4.1) which contains add a new  function `isInstalledModule` to the style API which checks if a module is resolvable and is contained in any `node_modules` directory. I hope it solves this issue.

**Comment by OliverJAsh** [comment]
Thank you! :-)

**Comment by renke** [comment]
The style receices a file parameter that should be used as base file.

**Comment by OliverJAsh** [comment]
Apologies but I can not see a file parameter that I can use as the base file. I'm looking at all the properties on `IStyleAPI`, which is what my style function receives as a parameter.

If you could provide an example of a style which uses this new function, that would be most helpful, so I can see how to provide a base file.

**Comment by OliverJAsh** [comment]
Aha, found it. `IStyle` has a second parameter `file`.
