### ISSUE TITLE
Error with comments

### ISSUE THREAD

**Issue by poorbug** [renke/import-sort#35]
[issue of vsc-sort-import](https://github.com/peterjuras/vsc-sort-imports/issues/25)

Before sorting:
<img width="1164" alt="2017-10-09 2 40 09" src="https://user-images.githubusercontent.com/5172464/31328507-273f8894-ac9b-11e7-8c43-a392aada36b7.png">

After sorting:
<img width="1171" alt="2017-10-09 2 40 21" src="https://user-images.githubusercontent.com/5172464/31328519-38352db6-ac9b-11e7-8ebc-075980251021.png">

**Comment by renke** [comment]
Hi @poorbug 

can you provide your code as text, so I can try to reproduce it?

**Comment by poorbug** [comment]
Hi, @renke 

```
// NativeModules.TTRNBridge = {log:()=>{}};NativeModules.TTRNDeviceInfo = { model: 'iPhone', appVersion: '6.3.0' };
import { consoleKiller } from './src/utils';
```

Thanks for your work.

**Comment by renke** [comment]
Hi @poorbug 

this will be fixed in the next major release. There was actually a bug that occurs when a leading comment contains something like `{ … }`.

Thanks for raising this issue!
