### ISSUE TITLE
Respect file line endings

### ISSUE THREAD

**Issue by michaelgeorgeattard** [renke/import-sort#37]
Hi,

First of all, awesome tool!

Currently import-sort is not respecting file line-endings. Would it be possible to do so?

If that makes sense for you I can create a PR with that functionality.

Thanks

**Comment by noelklein** [comment]
@michaelgeorgeattard what needs to be done to implement this? I think I'm running into some issues with line endings and running import-sort locally vs. on the continuous integration build agent machine.

**Comment by noelklein** [comment]
I guess it would just require to replace all `\n` with https://nodejs.org/api/os.html#os_os_eol

**Comment by renke** [comment]
Hi @noelklein 

I think the best way would be to detect the line ending used in the file that is being sorted. Using the OS line ending may cause problems for Windows users working together with Linux oder MacOS users. 

When I find some time I will fix this by using https://www.npmjs.com/package/detect-newline

**Comment by renke** [comment]
Hi @noelklein 

this is now part of major version 4. Let me know if works for you.

**Comment by michaelgeorgeattard** [comment]
Hi @renke, sorry for the late reply.

Unfortunately version 4.2.0 did not fix the issue. I am using typescript parser with a custom style if that makes any difference.
