### ISSUE TITLE
Import sort does not recognize flow comment

### ISSUE THREAD

**Issue by LarsKoelpin** [renke/import-sort#39]
As flow files typically begin with

```javascript
//@flow
```
They shall not be rearranged.

Non working example
```javascript
//@flow
import dotEnv from 'dotenv'
import {compile} from './geth'
import express from 'express'
```

Turns into
```javascript
import {compile} from './geth'
//@flow
import dotEnv from 'dotenv'
import express from 'express'
```

**Comment by renke** [comment]
Hi @LarsKoelpin 

this can be fixed by adding a blank line after copyright headers and compiler pragams. I will add an example to the README so other people don't run into the same problem.
