### ISSUE TITLE
How can I define a different default configuration?

### ISSUE THREAD

**Issue by amatiasq** [renke/import-sort#41]
https://github.com/renke/import-sort/blob/8641f7f364ae1fac2374fcd1182a8ea53f38f521/packages/import-sort-config/src/index.ts#L38

Or maybe use no default configuration so I get null when it's called.

I would like to call `getConfigFromPackage(directory, extension);` directly and get no default configuration but it's not exported. Maybe we can export it?

**Comment by renke** [comment]
Hi @amatiasq 

what would be the use case for this feature?

**Comment by amatiasq** [comment]
We're looking for a way to set `importSort` configuration at editor level for [the VSCode extension](https://github.com/amatiasq/vsc-sort-imports/issues/5) and this should have higher priority than the default configuration but lower than `package.json` configuration.

Separating the default configuration from the `package.json` reading process solves this issue.

**Comment by renke** [comment]
Ah, I see. This will be included in the next release then.
