### ISSUE TITLE
Support dynamic imports / code splitting.

### ISSUE THREAD

**Issue by sontek** [renke/import-sort#46]
I have a component like this:

```
const LoadableDesignPatterns = Loadable({
    loader: () => import('./design_patterns'),
    loading: Loading,
});

```

and `import-sort-cli` is crashing with:

```
SyntaxError: Unexpected token (85:18)
```

**Comment by renke** [comment]
Hi @sontek 

this should be fixed in the new minor version.

**Comment by PaulRBerg** [comment]
This doesn't look fixed. I am using the latest version of the [sort-imports](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports) extension for VSCode, and I am getting the same `Unexpected token` error when attempting to sort the imports in this file:

https://gist.github.com/paulrberg/29394b2188ea515448732d7a1fadb3dd
