### ISSUE TITLE
Not sorting imports correctly?

### ISSUE THREAD

**Issue by magicmark** [renke/import-sort#47]
Hi @renke ! Thanks for the project!

Running into an issue:

Here is my sample file:

```
import * as React from 'react';

import Counter from './Counter';
import { Provider } from 'react-redux';
import reducers from './reducers';
```

From `package.json`:
```
  "importSort": {
    ".js": {
      "parser": "babylon",
      "style": "eslint"
    }
  },
```

Running `import-sort` on this results in a noop. eslint will complain about this - I believe the line `import { Provider } from 'react-redux';` should come second?

(Side note - would be awesome to have a try-import-sort website to quickly paste this to demonstrate the issue, hint hint :D)

(Version information):
```
╔═ markl@xenialdev2-uswest1cdevc:
╚═ ♪ yarn list | grep import-sort
warning package.json: No license field
warning yelp-js-infra@21.0.0: No license field
├─ import-sort-cli@4.2.0
│  ├─ import-sort-config@^4.2.0
│  ├─ import-sort-parser@^4.2.0
│  ├─ import-sort-style@^4.2.0
│  ├─ import-sort@^4.2.0
├─ import-sort-config@4.2.0
├─ import-sort-parser-babylon@3.2.0
├─ import-sort-parser@4.2.0
├─ import-sort-style-eslint@4.2.0
├─ import-sort-style@4.2.0
├─ import-sort@4.2.0
│  ├─ import-sort-parser@^4.2.0
│  ├─ import-sort-style@^4.2.0
```

Thanks!

**Comment by renke** [comment]
Hi @magicmark,

yes, the ESLint style is not really working 100% as of now. I created an issue for this #67 so we can fix it.
