### ISSUE TITLE
Add support for comments in import statements

### ISSUE THREAD

**Issue by k2snowman69** [renke/import-sort#49]
First let me say, awesome project! Love the flexibility you can get going with this! I do have one request in regards to readability for code reviews, it would be great if it were possible to add comments after separators so that each import group would be named. For example:
```
// Absolute modules with side effects (not sorted because order may matter)
import "a";
import "c";
import "b";

// Relative modules with side effects
import "./a";
import "./c";
import "./b";

// File store stuff
import {readFile, writeFile} from "fs";
import * as path from "path";

// External imports
import aa from "aa";
import bb from "bb";
import cc from "cc";
import PropTypes from "prop-types";
import React from "react";
import { connect } from "react-redux";

// Relative imports
import aaa from "../../aaa";
import bbb from "../../bbb";
import aaaa from "../aaaa";
import bbbb from "../bbbb";
import aaaaa from "./aaaaa";
import bbbbb from "./bbbbb";
import styles from "./Component.scss";
```

But when you save this file using the module style you end up with
```
// Absolute modules with side effects (not sorted because order may matter)

import "a";
import "c";
import "b";

import "./a";
import "./c";
import "./b";

import {readFile, writeFile} from "fs";
import * as path from "path";

import aa from "aa";
import bb from "bb";
import cc from "cc";
import PropTypes from "prop-types";
import React from "react";
import { connect } from "react-redux";

import aaa from "../../aaa";
import bbb from "../../bbb";
import aaaa from "../aaaa";
import bbbb from "../bbbb";
import aaaaa from "./aaaaa";
import bbbbb from "./bbbbb";
import styles from "./Component.scss";

// Relative modules with side effects




// File store stuff



// External imports







// Relative imports








```

It would be great if the comments were preserved and could even be generated. To do this I figure you need a new setting, something like deleteCommentsInImports just so you know to delete the comments in the imports section before doing the actual sort. Second a new field similar to Separator called Header (or something) and then you just generate the headers.

This way, when the code goes to code review, the imports aren't just sorted, they are also documented a bit to make life easier.

**Comment by rickyp-uber** [comment]
Maybe a possible alternate solution would be to allow sorting only selected imports? So you can select the imports you want to sort, then run the command to sort them? I know it's not as easy to run but based on reading the code, it should be easier to implement.

**Comment by renke** [comment]
I think that's a pretty good idea, but I would take a lot of work to implement this (for it not to be too brittle). I will keep your idea in mind though.

Regarding your second comment, only sorting parts of file could actualy be implemented right now by editor plugins that use `import-sort`. It only really needs a valid JS/TS code fragment that can be parsed by the parser in queston.
