### ISSUE TITLE
Extra line added before first import in .vue SFC

### ISSUE THREAD

**Issue by rndmerle** [renke/import-sort#52]
Hi.

I wasn't expecting it but it's actually working with VueJS SFC files!
The only little "issue" is that a blank line is added between the <script> tag and the first import.
It's not a big deal but It's better to report it.
Thanks for your time.

**.importsortrc:**
```
{
    ".vue, .ts": {
      "parser": "typescript",
      "style": "module"
    }
}
```

**Initial Module.vue**
```
<script lang="ts">
import Vue from "vue";
// ...
```

**Command**
`yarn run import-sort --write Module.vue`

**Expected result**
```
<script lang="ts">
import Vue from "vue";
// ...
```

**Actual result**
```
<script lang="ts">

import Vue from "vue";
// ...
```

**Comment by renke** [comment]
Hi @rndmerle 

can you send me a complete .vue file as "test data" for me? – Maybe I can fix your issue then.

**Comment by rndmerle** [comment]
Here is one. Thanks :)
```
<template>
    <div class="badge">
        <span v-if="content" :class="labelPositioning">{{ content }}</span>
        <slot></slot>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";

@Component
export default class Badge extends Vue {
    @Prop() content: string;

    get labelPositioning(): string {
        return this.$slots.default ? "hooked" : "free";
    }
}
</script>
```

**Comment by Airkro** [comment]
same problem, in VSCode

**Comment by renke** [comment]
Let's discuss this in #66 – actual support for Vue would be great.
