### ISSUE TITLE
Add support for style configuration through json

### ISSUE THREAD

**Issue by haroldma** [renke/import-sort#56]
sample of feature:

```
 [
  { 'match': [ 'noMembers', 'absoluteModule' ] },
  { 'separator': true }

  { 'match': [ 'noMembers', 'relativeModule' ] },
  { 'separator': true }
  {
     match: [ 'nodeModule' ],
     sort: [ 'name' ],
     sortNamedMembers:  [ 'alias' ]
  },
  { separator: true },
  {
     match: [ 'scopedModule', 'absoluteModule' ],
     sort: [ 'name' ],
     sortNamedMembers:  [ 'alias' ]
  },
  { separator: true },
]
```

no need for the overkill of creating a whole separate package!

**Comment by renke** [comment]
Hi @haroldma 

This would be a lot of work to implement, because a style is actual code that needs to be executed. In future thought I will try to make it easier to include custom styled on a per-project basis.

**Comment by Floriferous** [comment]
This would be awesome, and is what I'm looking for.

TypeScript Import Sorter does this, but sadly only for .ts files. https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter
