### ISSUE TITLE
Something wrong in .vue SFC with `v-for`

### ISSUE THREAD

**Issue by Airkro** [renke/import-sort#57]
In my case, it's working fine, but something wrong in .vue SFC.

```js
// .importsortrc
// my rules: https://github.com/Airkro/import-sort-style-airkro
{
  ".js": {
    "parser": "babylon",
    "style": "airkro"
  },
  ".vue": {
    "parser": "typescript",
    "style": "airkro"
  }
}
```

In my rules, I prefer move css file to last line. 
But in following code, it won't do that.

```vue
<template>
  <div>
    <div
      :key="a"
      v-for="a in b"
    />
  </div>
</template>

<script>
import 'style.css';

import lodash from 'lodash';
</script>
```

Unless i put something with `:` symbol after `v-for`.

```vue
<template>
  <div>
    <div
      :key="a"
      v-for="a in b"
      :test="1"
    />
  </div>
</template>

<script>
import lodash from 'lodash';

import 'style.css';
</script>
```

**Comment by Airkro** [comment]
Now we know this plugin working in .vue (with `typescript` parser). but still have labile factor. 
maybe we need another parser only handle the script tag. then we can use `babylon` parser in .vue

**Comment by renke** [comment]
Let's discuss this in #66 – Vue is not really supported currently.
