### ISSUE TITLE
please add ignored file list for auto-save

### ISSUE THREAD

**Issue by LucaColombi** [renke/import-sort#62]
in some case the order of import matters, it is rare but when it happens I have to switch off sort on save in all the IDE to let the single file work.

A simple solution would be to have a setting where I can put ignored file as a list of file names

Can you implement this?

**Comment by jquense** [comment]
We added this in our fork, and the comment is really a better option i think, vs a whitelist

**Comment by renke** [comment]
This is now supported in v6 via comments `// import-sort-ignore` or `/* import-sort-ignore */`.
