### ISSUE TITLE
Flow comment annotations

### ISSUE THREAD

**Issue by warpr** [renke/import-sort#65]
Looks like [Flow comment annotations](https://flow.org/en/docs/types/comments/) are not supported.  import-sort just turned this:

```javascript
import { parseCue /*:: type CueRecord */ } from '/lud/cue.js';
```

into this:

```javascript
import { parseCue } from '/lud/cue.js';
```

This is my `.importsortrc.json`:

```json
{
    ".js, .jsx": {
        "parser": "babylon",
        "style": "module"
    }
}
```

**Comment by warpr** [comment]
For anyone else running into this, looks like a workaround is to use entirely separate lines:

```javascript
/*::
import { type CueRecord } from '/lud/cue.js';
*/
import { parseCue } from '/lud/cue.js';
```

**Comment by gwing33** [comment]
It's not just comment annotations, it's type declarations within the curlies...

```js
// Before import sort
import { type MyType } from './MyType'

// After import sort
import { MyType } from './MyType'
```

```js
// This works fine
import type { MyType } from './MyType'
```

**Comment by renke** [comment]
This should work in the next release (thanks to #48.)
