### ISSUE TITLE
Fix ESLint style

### ISSUE THREAD

**Issue by renke** [renke/import-sort#67]
The ESLint style is not really working as expected. It should always sort the imports such that it complies with ESLint's rules. We might have to actually read ESLint config to do this properly.

**Comment by paulius005** [comment]
Hey @renke can you point me in the right direction on how to start solving this issue?

I would love to contribute and this would be a huge win for code standards for the Loom folks.

**Comment by Southclaws** [comment]
I'm running into this currently on https://github.com/openmultiplayer/homepage/tree/master/pages/_app.jsx it doesn't seem to separate external modules from internal, so eslint is warning about internal stuff coming before external stuff.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1636971/68670013-c25c5480-0543-11ea-8d84-77432c362eb2.png">
