### ISSUE TITLE
Trailing comma (was: sorting with unexpected results after update)

### ISSUE THREAD

**Issue by bruno12mota** [renke/import-sort#7]
Hey! Great work with this plugin. Using it for some months now 😄  Dunno what happened, probably some update on the package or the atom itself the sort is giving wrong results, such as:

Initial (which is correct with the expected):

``` js
import utils from 'helpers/utils';
import Droppable from 'components/dnd/droppable';
import React, {PropTypes} from 'react';

import classes from './classes';
import style from './style';
import propsSchema from './props-schema';
import settings from './settings';
import Component from '../component';
import Element from '../element';
```

On save it will re order to:

``` js
import React, {PropTypes} from 'react';

import Component from '../component';
import Droppable from 'components/dnd/droppable';
import Element from '../element';
import classes from './classes';
import propsSchema from './props-schema';
import settings from './settings';
import style from './style';
import utils from 'helpers/utils';
```

So it seems to be joining relative and absolute path imports. Any clue why this is happening?

**Comment by bruno12mota** [comment]
Also, multiline imports are appending a trailing comma to the end.

Initial

```js
import {
  GraphQLBoolean,
  GraphQLID,
  GraphQLNonNull,
  GraphQLString
} from 'graphql';
```

After sorting

```js
import {
  GraphQLBoolean,
  GraphQLID,
  GraphQLNonNull,
  GraphQLString,
} from 'graphql';
```

Which wasn't happening before as well

**Comment by renke** [comment]
Hi @bruno12mota 

thanks for the kind words. Yes. you are right, import-sort was updated to a new major version and a few things changed. Have a look at https://github.com/renke/atom-import-sort/issues/10 which explains how to get back the old style.

However, trailing comma is currently not configurable :cry:, sorry.

**Comment by bruno12mota** [comment]
Oh nice, thanks 😄  and sorry didn't check that issue

Trailing comma is a bummer but not totally critical for me. Would be nice to have as an option though

**Comment by renke** [comment]
Hi @bruno12mota 

a trailing comma is now only added if it was put there in the first place.
