### ISSUE TITLE
Feature-Req: Support for sorting exports

### ISSUE THREAD

**Issue by githendrik** [renke/import-sort#73]
I'm using your tool in a few projects as a pre-commit hook, and really appreciate not having to worry about the import order. Thanks!

Would it be possible to add support for sorting exports as well?

**Comment by renke** [comment]
Hi @githendrik 

unfortunately, sorting exports it not really feasible because the order of exports can matter and it is hard to know when that's the case.

**Comment by fenderface66** [comment]
@githendrik I am trying to do the same thing (run the tool as a pre-commit hook) but cannot get it to work. Would you be able to share your code as to how you got it running?

**Comment by githendrik** [comment]
@fenderface66 not sure if here is the correct place to answer, but: https://gist.github.com/githendrik/a064f38e2b7c4616eb123356db0a7786

HTH

**Comment by fenderface66** [comment]
@githendrik Thanks so much! Works great!

**Comment by kiewic** [comment]
Hi, 

I haven't deal with a case where exports order matter yet. I imagine there are a lot of places where it does not matter. Would it be possible to add an option to sort exports only when a user requests it?
