### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by OliverJAsh** [renke/import-sort#81]
Hi @renke. I'm looking to upgrade our version of import-sort soon, however I noticed there's no changelog. Would it be possible to create one for future reference?

In the meantime, do you know if there are any breaking changes between 4.2.0 and the current version (6.0.0), before I attempt the upgrade?

Thanks

**Comment by renke** [comment]
Hi @OliverJAsh 

sorry for the late response. I am currently not maintaining a change log, but I usually try to have meaningful commit messages. Other than that, you could probably look at the changes to the README to see any major changes/additions. For library usage of `import-sort` I try to avoid breaking changes, the CLI on the other hand changed significantly in the past.
