### ISSUE TITLE
Change only if needed

### ISSUE THREAD

**Issue by jerrygreen** [renke/import-sort#85]
It's annoying the lib commits/pushes a change to my buffer on **every** save.

With autosave on focus, it's getting annoying quickly, because even if my imports are already sorted correctly - the extension pushes some "nothing changed" event to my buffer, and if I want `cmd/ctrl + z`, I stuck into blank changes every time.

It should commit changes only if there's something to sort. Not every save.

**Comment by renke** [comment]
Hi @JerryGreen 

what editor are you using? – for Visual Studio Code, it's probably a better to create an issue here https://github.com/amatiasq/vsc-sort-imports

**Comment by jerrygreen** [comment]
@renke yea, VSCode. Anyway, I’m using tslint for this feature (it has automatic fixes, and it runs on file save). It’s probably going to be deprecated and replaced with eslint but for now it’s ok, I don’t have this issue now
