### ISSUE TITLE
merge imports

### ISSUE THREAD

**Issue by ggascoigne** [renke/import-sort#99]
Is there any chance on having an option to merge imports?

I'd like to be able to collapse:

```js
import { foo_one } from './bar'
import { foo_two } from './bar'
```

into:

```js
import { foo_one, foo_two } from './bar'
```

Or am I missing an existing option?

**Comment by renke** [comment]
Hi @ggascoigne 

no, this not currently supported. I am not sure if this should be part of import-sort actually. I think a lot of tools already support some kind of "Organize imports" functionality, I think the TS language server itself has this functionality.
